apiVersion: v1
kind: Service
metadata:
  name:  tkcicd-rtp-service
  namespace: tkcicd
spec:
  type: NodePort
  selector:
    app: tkcicd-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000